# Generated by Django 4.2.1 on 2023-06-06 07:52

import apps.movies_and_series.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0004_alter_actor_photo_alter_director_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.FileField(null=True, upload_to=apps.movies_and_series.utils.videos_uploaded, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Эпизод'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to=apps.movies_and_series.utils.videos_uploaded, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Фильм'),
        ),
    ]
