# Generated by Django 4.2.1 on 2023-06-06 11:23

import apps.movies_and_series.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0005_alter_episode_episode_alter_movie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(upload_to=apps.movies_and_series.utils.upload_instance, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='director',
            name='photo',
            field=models.ImageField(upload_to=apps.movies_and_series.utils.upload_instance, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.FileField(upload_to=apps.movies_and_series.utils.videos_uploaded, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Эпизод'),
        ),
    ]
