# Generated by Django 4.2.1 on 2023-06-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0007_alter_actor_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода на сайте'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода на сайте'),
        ),
    ]
