# Generated by Django 4.2.1 on 2023-06-06 19:41

import apps.movies_and_series.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0008_alter_movie_release_date_alter_tvshow_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=apps.movies_and_series.utils.upload_instance, verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='episode',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to=apps.movies_and_series.utils.videos_uploaded, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Трайлер эпизода'),
        ),
    ]
