# Generated by Django 4.2.1 on 2023-06-07 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0011_alter_episode_poster_alter_episode_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='release_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата выхода на сайте'),
            preserve_default=False,
        ),
    ]
