# Generated by Django 4.2.1 on 2023-06-07 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0012_episode_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 18, 51, 42, 791277, tzinfo=datetime.timezone.utc), verbose_name='Дата выхода на сайте'),
        ),
    ]
