# Generated by Django 4.2.1 on 2023-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0013_alter_episode_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateField(verbose_name='Дата выхода на сайте'),
        ),
    ]
