# Generated by Django 4.2.1 on 2023-06-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0014_alter_episode_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='release_date',
        ),
    ]
