# Generated by Django 4.2.1 on 2023-06-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0017_alter_episode_episode_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_release_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выхода на сайте'),
        ),
    ]
