# Generated by Django 4.2.1 on 2023-06-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0022_alter_movie_rating_alter_tvshow_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='trailer',
        ),
    ]
