# Generated by Django 4.2.1 on 2023-06-15 13:34

import apps.movies_and_series.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0023_remove_episode_poster_remove_episode_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=apps.movies_and_series.utils.upload_instance, verbose_name='Постер'),
        ),
    ]
