# Generated by Django 4.2.1 on 2023-06-15 13:36

import apps.movies_and_series.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0025_alter_episode_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='poster',
            field=models.ImageField(default=1, upload_to=apps.movies_and_series.utils.upload_instance, verbose_name='Постер'),
            preserve_default=False,
        ),
    ]
