# Generated by Django 4.2.1 on 2023-06-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date_of_birth_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=None, null=True, verbose_name='Активный'),
        ),
    ]
