# Generated by Django 4.2.1 on 2023-06-05 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_subscription_subscription_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата покупки'),
        ),
    ]
