# Generated by Django 4.2.1 on 2023-06-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_purchase_options_alter_purchase_subscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviereview',
            options={'verbose_name': 'Отзыв к фильму', 'verbose_name_plural': 'Отзывы к фильмам'},
        ),
        migrations.AlterModelOptions(
            name='tvshowreview',
            options={'verbose_name': 'Отзыв к сериалу', 'verbose_name_plural': 'Отзывы к сериалам'},
        ),
        migrations.RenameField(
            model_name='tvshowreview',
            old_name='movie',
            new_name='tvshow',
        ),
    ]
