# Generated by Django 4.2.1 on 2023-06-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_series', '0011_alter_episode_poster_alter_episode_trailer'),
        ('users', '0013_alter_moviereview_options_alter_tvshowreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='content_access_day',
            field=models.IntegerField(default=0, verbose_name='Через сколько дней доступен, контент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='users', to='movies_and_series.genre', verbose_name='Подписка'),
        ),
    ]
